name: Deploy

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  deploy:
    - uses: BevisOrg/cicd/.github/workflows/run-docker.yml@master
      with:
        service_name: admin-portal
      secrets: inherit
