name: Deploy

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  deploy:
    uses: BevisOrg/cicd/.github/workflows/build.yml@master
    with:
      service_name: admin-portal
      env: PROD
    secrets: inherit
