name: Deploy

on:
  push:
    branches: master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: BevisDev/cicd/.github/workflows/run.yml@master
    with:
      service_name: admin-portal
    secrets: inherit
